services:
  db:
    image: postgres:16-alpine
    container_name: db
    networks:
      - apinetwork
    expose:
      - 5432
    ports:
      - "5422:5432"
    volumes:
      - dbasedata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: miniblogger
      POSTGRES_PASSWORD: miniblogg
      POSTGRES_DB: blogdb
  api:
    image: bryanney/minibloggingapp:1.0.0
    build: ./backend
    container_name: api
    depends_on:
      - db
    networks:
      - apinetwork
    env_file:
      - .env.dev
    ports:
      - "5000:5000"
    links:
      - db:db
volumes:
  dbasedata:
networks:
  apinetwork:
    driver: bridge
