services:
  testdb:
    image: postgres:16-alpine
    container_name: testdb
    networks:
      - testapinetwork
    expose:
      - 5432
    ports:
      - "5424:5432"
    volumes:
      - testdbdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: bloggertest
      POSTGRES_PASSWORD: testblogger
      POSTGRES_DB: testblogdb
  test1api:
    image: bryanney/minibloggingapp:1.0.0
    restart: always
    build: ./backend
    container_name: test1api
    depends_on:
      - testdb
    networks:
      - testapinetwork
    env_file:
      - .env.test
    ports:
      - "5050:5050"

volumes:
  testdbdata:
networks:
  testapinetwork:
    driver: bridge
